name: "MunkiPkg Action"
author: "joncrain"
description: "GitHub Action to build a macOS package for release."

branding:
  icon: "command"
  color: "gray-dark"

outputs:
  pkg-version:
    value: ${{ steps.munkipkg.outputs.tag }}
    description: "Returns the pkg version from the build-info file."
  pkg-name:
    value: ${{ steps.munkipkg.outputs.filename }}
    description: "Returns the filename of the built pkg."
  pkg-path:
    value: ${{ steps.munkipkg.outputs.filepath }}
    description: "Returns the filepath of the built pkg."

runs:
  using: "composite"
  steps:
    - id: munkipkg
      run: |
        curl https://raw.githubusercontent.com/munki/munki-pkg/main/munkipkg -o ${{ github.action_path }}/munkipkg
        chmod +x ${{ github.action_path }}/munkipkg
        ${{ github.action_path }}/munkipkg "$GITHUB_WORKSPACE"
        if [ -f "$GITHUB_WORKSPACE"/build-info.json ]; then
          version=$(jq -r .version "$GITHUB_WORKSPACE"/build-info.json)
        elif [ -f "$GITHUB_WORKSPACE"/build-info.plist ]; then
          version=$(defaults read "$GITHUB_WORKSPACE"/build-info.plist version)
        elif [ -f "$GITHUB_WORKSPACE"/build-info.yaml ]; then
          version=$(grep -A3 'version:' "$GITHUB_WORKSPACE"/build-info.yaml | tail -n1 | awk '{ print $2}' | sed "s/\'//g")
        fi
        echo "::set-output name=tag::$(echo v${version})"
        for file in "$GITHUB_WORKSPACE"/build/*; do
          echo "::set-output name=filename::$(echo "${file##*/}")"
          echo "::set-output name=filepath::$(echo "$GITHUB_WORKSPACE/build/${file##*/}")"
        done
      shell: bash
